### ISSUE TITLE
BUg: DocList.to_dataframe

### ISSUE THREAD

**Issue by yuanjie-ai** [docarray/docarray#1463]
![image](https://user-images.githubusercontent.com/20265321/234743810-6753a686-2c84-417d-8723-0414cd14da39.png)

**Comment by JoanFM** [comment]
Copying code here:

```python
from docarray import DocList, BaseDoc
from docarray.typing import TorchTensor
from docarray.utils.find import find
from docarray.utils.filter import filter_docs

import torch


class Doc(BaseDoc):
    text: str
    embedding: TorchTensor


query = torch.rand(128)

index = DocList[BaseDoc]([Doc(text=_, embedding=torch.rand(128)) for _ in range(100)])

r = find(index=index, query=query, search_field='embedding', metric='cosine')

top_matches, score = r
top_matches.to_dataframe()
```

**Comment by samsja** [comment]
Hey @yuanjie-ai . This is not a bug per see. Indeed you can only convert a DocList to a dataframe if the DocList is homogenous, i.e, if all of the Document inside follow the same schema. The reason is that we need to create the dataframe table before hand.

In your case you will need to do something like this.

```python
top_matches = DocList[type(top_matches[0])](top_matches)
top_matches.to_dataframe()
```

We will see later if we cannot introduce a `unwrap_homegenous()` method that would do exactly this.

Nevertheless the error message is def'ly not clear. I am fixing it in this PR https://github.com/docarray/docarray/pull/1467
