### ISSUE TITLE
feat: add a `to_doc_list_view` method to DocVec

### ISSUE THREAD

**Issue by samsja** [docarray/docarray#1564]
# Context

When calling `to_doc_list` on a DocVec it destroys (deletes) the storage of DocVec and therefore the DocVec is not usable.

But in some case we could want to create a DocList out of the DocVec without destroying the DocVec.

## What we could do

we could introduce two new method on DocVec:

* `to_doc_list_view` which will create a DocList of Document view and will keep the DocVec intact. 
*  `to_doc_list_copy` which will create  DocList by copying the Document from the DocVec View and keep the DocVec intact

**Comment by JohannesMessner** [comment]
> in some case

What cases are you thinking of?

> to_doc_list_view

How would this work? How would insertions, re-shuffling etc be handled? We had a reason not to expose those APIs on DocVec, but creating a view on the DocVec data would just face the same problems, no?

> to_doc_list_copy

Why not just `copy.deepcopy(doc_vec).to_doc_list()`?

**Comment by JohannesMessner** [comment]
But then what happens to the underlying DocVec if you add a new document to the List view? Nothing, right? And the view will have a list-like interface with a column-wise memory layout, it will make everything inefficient, right? To me it is a bit of an anti pattern and confusing tbh. But maybe we can document this trick (DocList[self.doc_type]([doc for doc in self])) in an `advanced` section somewhere?

> lets say I have a function that works only with DocList

If it really doesn't work even with ducktyping then it means that you are doing operations that DocVec is not meant to do. In that case I think you need to refactor your code instead of us giving you a way to do those operations anyways. To me it goes against the principle of separation of concerns that we introduced with the List/Vec split. This would go back to having one class (in this case, the view) that can be either row-wise or column-wise, and there were a number of pitfalls that made us move away from that. I am worried that this would just bring back all of those problems.

**Comment by JohannesMessner** [comment]
> But technically what I am proposing would be the equivalent of doing this with pytorch
Yes, and I am saying the user can feel free to do the same with docarray; but pytorch doesn't have a helper for this, and neither should we ;)

**Comment by samsja** [comment]
fair fair
