### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by JoanFM** [docarray/docarray#1825]
# Release Note

This release contains 2 bug fixes.

### From_dataframe with numpy==1.26.1 (#1823)
A recent update to numpy has changed some of the versioning semantics, breaking DocArray's `from_dataframe()` method in some cases where the dataframe contains a numpy array. This has now been now fixed.

```python
class MyDoc(BaseDoc):
    embedding: NdArray
    text: str

da = DocVec[MyDoc](
    [
        MyDoc(
            embedding=[1, 2, 3, 4],
            text='hello',
        ),
        MyDoc(
            embedding=[5, 6, 7, 8],
            text='world',
        ),
    ],
    tensor_type=NdArray,
)
df_da = da.to_dataframe()
# This broke before and is now fixed
da2 = DocVec[MyDoc].from_dataframe(df_da, tensor_type=NdArray)
```

### Type handling in python 3.9 (#1823)

Starting with Python 3.9, `Optional.__args__` is not always available, leading to some compatibility problems. This has been fixed by using the `typing.get_args` helper.

## 🤟 Contributors

We would like to thank all contributors to this release:
- Johannes Messner (@JohannesMessner )

**Comment by scott-martens** [comment]
"Type handling in python 3.9" has no bug ticket?

**Comment by scott-martens** [comment]
Change "Starting from Python 3.9, `Optional.__args__` is not always available, leading to breaking code paths in our code base. This fixes that by utilizing the `typing.get_args` helper."

To: "Starting with Python 3.9, `Optional.__args__` is not always available, leading to come compatibility problems. This has been fixed by using the `typing.get_args` helper."

**Comment by scott-martens** [comment]
# Release Note

This release contains 1 bug fix.

## :ladybug: Bug Fixes

### From_dataframe with numpy==1.26.1 (#1823)
A recent update to numpy has changed some of the versioning semantics, breaking DocArray's `from_dataframe()` method in some cases where the dataframe contains a numpy array. This has now been now fixed.

```python
class MyDoc(BaseDoc):
    embedding: NdArray
    text: str

da = DocVec[MyDoc](
    [
        MyDoc(
            embedding=[1, 2, 3, 4],
            text='hello',
        ),
        MyDoc(
            embedding=[5, 6, 7, 8],
            text='world',
        ),
    ],
    tensor_type=NdArray,
)
df_da = da.to_dataframe()
# This broke before and is now fixed
da2 = DocVec[MyDoc].from_dataframe(df_da, tensor_type=NdArray)
```

### Type handling in python 3.9 (#1823)

Starting with Python 3.9, `Optional.__args__` is not always available, leading to some compatibility problems. This has been fixed by using the `typing.get_args` helper.

## :i_love_you_hand_sign: Contributors

We would like to thank all contributors to this release:
- Johannes Messner (@JohannesMessner )
